name: Auto Format

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-format:
    name: Auto Format Code
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.type != 'Bot'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Pint (PHP formatting)
        run: vendor/bin/pint

      - name: Run Prettier (Frontend formatting)
        run: npm run format

      - name: Run ESLint (Frontend linting)
        run: npm run lint

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "style: auto-format code with pint and prettier"
          git push

      - name: Comment on PR
        if: steps.git-check.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 I\'ve automatically formatted your code to match our style guidelines. The changes have been committed to your branch.'
            })
